// Golden Family Heritage — Family Data
// Generated from 39 hand-written ancestry charts
// Uncertain readings are marked with [brackets]

const PEOPLE = {
  // ── GENERATION 0 (Parents of oldest confirmed ancestors) ──────────────────
  "p001": { id:"p001", first:"Jean", last:"Johnson", gender:"M", birth:{}, death:{}, notes:"Father of Benoit Johnson" },
  "p002": { id:"p002", first:"Marceline", last:"McLean", gender:"F", birth:{}, death:{}, notes:"Mother of Benoit Johnson" },
  "p003": { id:"p003", first:"Dave", last:"Clack", gender:"M", birth:{}, death:{}, notes:"Father of Louise Clack (chart 22)" },
  "p004": { id:"p004", first:"Mela", last:"Hebert", gender:"F", birth:{}, death:{}, notes:"Mother of Louise Clack (chart 22)" },

  // ── GENERATION 1 (Oldest with their own charts) ───────────────────────────
  "p010": { id:"p010", first:"Albert", last:"Golden", gender:"M",
            birth:{date:"c.1850", place:"Nashville, TN"}, death:{date:"c.1907", place:"Graveton, TX"},
            chartRef:[14], notes:"" },
  "p011": { id:"p011", first:"Ella", last:"Littleton", gender:"F",
            birth:{date:"c.1870", place:"Grouse, TX"}, death:{date:"c.1899", place:"Graveton, TX"},
            chartRef:[14], notes:"Wife of Albert Golden" },
  "p012": { id:"p012", first:"Charles Frederick", last:"Banks", gender:"M",
            birth:{place:"Germany"}, death:{},
            chartRef:[23], notes:"Military: Private, LA Infantry" },
  "p013": { id:"p013", first:"Celestine", last:"Aymond", gender:"F",
            birth:{}, death:{}, chartRef:[23], notes:"Wife of Charles Frederick Banks" },
  "p014": { id:"p014", first:"Benoit", last:"Johnson", gender:"M",
            birth:{date:"c.1852", place:"Mamou, LA (Evangeline Parish)"},
            death:{date:"c.2/1/1915", place:"Tucker Creek, LA"},
            chartRef:[21,22], notes:"Church of Christ. Possibly married twice: Susan Clack and Louise Clack." },
  "p015": { id:"p015", first:"Louise", last:"Clack", gender:"F",
            birth:{place:"[Tulie Cove, LA]"}, death:{},
            chartRef:[22], notes:"Wife of Benoit Johnson; mother of Alice Johnson" },
  "p016": { id:"p016", first:"Susan", last:"Clack", gender:"F",
            birth:{date:"c.2/21/1851"}, death:{date:"c.2/1/1917"},
            chartRef:[21], notes:"Possibly first wife of Benoit Johnson" },
  "p017": { id:"p017", first:"Rev. George H.", last:"Barrett", gender:"M",
            birth:{place:"Mississippi"}, death:{},
            chartRef:[19], notes:"Occupation: Preacher; Church: Baptist; Place: Mississippi" },
  "p018": { id:"p018", first:"Sarah", last:"Barrett", gender:"F",
            birth:{}, death:{}, chartRef:[19], notes:"Wife of Rev. George H. Barrett" },
  "p019": { id:"p019", first:"Edward M.", last:"White", gender:"M",
            birth:{date:"c.1852"}, death:{date:"c.1899", place:"Shiloh Cemetery"},
            chartRef:[20], notes:"" },
  "p020": { id:"p020", first:"Nancy Ann", last:"Hall", gender:"F",
            birth:{}, death:{place:"Shiloh Cemetery"},
            chartRef:[20], notes:"Wife of Edward M. White" },
  "p021": { id:"p021", first:"William Joseph", last:"Brown", gender:"M",
            birth:{}, death:{}, chartRef:[18], notes:"" },
  "p022": { id:"p022", first:"Berta Lou Mildred", last:"Evans", gender:"F",
            birth:{}, death:{date:"c.2/1/1953"}, chartRef:[18], notes:"Wife of William Joseph Brown" },

  // ── GENERATION 2 ──────────────────────────────────────────────────────────
  "p030": { id:"p030", first:"James Edward", last:"Golden", gender:"M",
            birth:{date:"2/11/1887", place:"Hicks, TX (Burleson Co.)"},
            death:{date:"4/4/1939", place:"Beaumont, TX (Old Hardin City Cemetery)"},
            marriage:{date:"9/30/1911", place:"Lake Charles, LA"},
            chartRef:[12], notes:"Father: Albert Golden; Mother: Ella Littleton" },
  "p031": { id:"p031", first:"Beatrice Rebecca", last:"Banks", gender:"F",
            birth:{date:"4/1/1883", place:"[Lake Charles area], LA"},
            death:{date:"11/8/1944", place:"Kountze, TX (Old Hardin City Cemetery)"},
            chartRef:[12], notes:"Church: Episcopal. Daughter of Robert E. Lee Herman Banks + Alice Johnson" },
  "p032": { id:"p032", first:"Robert E. Lee Herman", last:"Banks", gender:"M",
            birth:{date:"7/21/1866", place:"Rapides Parish, LA"},
            death:{date:"[c.1932]", place:"Forest Hill, LA (Butler Cemetery)"},
            chartRef:[15,23], notes:"Father: Charles Frederick Banks; Mother: Celestine Aymond" },
  "p033": { id:"p033", first:"Alice", last:"Johnson", gender:"F",
            birth:{date:"10/11/1874", place:"Rapides Parish, LA"},
            death:{place:"Forest Hill, LA (Butler Cemetery)"},
            chartRef:[15,22], notes:"Daughter of Benoit Johnson + Louise Clack" },
  "p034": { id:"p034", first:"Henry Benson", last:"Barrett", gender:"M",
            birth:{place:"Mississippi"},
            death:{date:"c.2/1/1943", place:"[Tucker Creek, LA]"},
            chartRef:[13,19], notes:"Son of Rev. George H. Barrett + Sarah" },
  "p035": { id:"p035", first:"Elizabeth Jane", last:"White", gender:"F",
            birth:{date:"c.7/16/1836", place:"[Rapides Parish, LA]"},
            death:{date:"c.11/1943", place:"Beaumont, TX"},
            chartRef:[13,20], notes:"Daughter of Edward M. White + Nancy Ann Hall" },
  "p036": { id:"p036", first:"Aby Luther", last:"Barrett", gender:"M",
            birth:{date:"c.4/11/1904", place:"[Louisiana]"},
            death:{date:"c.11/17/1927", place:"Beaumont, TX (Forest Lawn Cemetery)"},
            chartRef:[11,13], notes:"Son of Henry Benson Barrett + Elizabeth Jane White" },
  "p037": { id:"p037", first:"Nora Lee", last:"Brown", gender:"F",
            birth:{date:"c.4/12/1905", place:"Many, LA (Sabine Parish)"},
            death:{date:"c.4/4/1936", place:"Beaumont, TX (Forest Lawn Cemetery)"},
            chartRef:[11,18], notes:"Daughter of William Joseph Brown + Berta Lou Mildred Evans" },
  "p038": { id:"p038", first:"Frances (Fannie)", last:"Golden", gender:"F",
            birth:{}, death:{}, chartRef:[16], notes:"Daughter of Albert Golden + Ella Littleton" },
  "p039": { id:"p039", first:"Dee", last:"Babin", gender:"M",
            birth:{}, death:{}, chartRef:[16], notes:"Husband of Frances (Fannie) Golden" },
  "p040": { id:"p040", first:"Kitty", last:"Golden", gender:"F",
            birth:{}, death:{}, chartRef:[17], notes:"Daughter of Albert Golden + Ella Littleton" },
  "p041": { id:"p041", first:"[?]", last:"Bransford", gender:"M",
            birth:{}, death:{}, chartRef:[17], notes:"Husband of Kitty Golden" },

  // Banks siblings (from chart 15)
  "p042": { id:"p042", first:"[Louisianafarrel]", last:"Banks", gender:"F",
            birth:{}, death:{}, chartRef:[23], notes:"Daughter of Charles Frederick Banks + Celestine Aymond" },
  "p043": { id:"p043", first:"Mary", last:"Banks", gender:"F",
            birth:{}, death:{}, chartRef:[23], notes:"Daughter of Charles Frederick Banks + Celestine Aymond" },

  // Barrett siblings (from chart 13)
  "p044": { id:"p044", first:"William Walter", last:"Barrett", gender:"M",
            birth:{}, death:{}, chartRef:[13], notes:"Son of Henry Benson Barrett + Elizabeth Jane White" },
  "p045": { id:"p045", first:"Nancy Evie", last:"Barrett", gender:"F",
            birth:{place:"Grant Parish, LA"}, death:{}, chartRef:[13], notes:"" },
  "p046": { id:"p046", first:"J. Eugene", last:"Barrett", gender:"M",
            birth:{date:"c.4/1/1863", place:"Grant Parish, LA"}, death:{}, chartRef:[13], notes:"" },
  "p047": { id:"p047", first:"Henry Lee", last:"Barrett", gender:"M",
            birth:{date:"c.6/1/1866", place:"Grant Parish, LA"}, death:{}, chartRef:[13], notes:"" },
  "p048": { id:"p048", first:"Minnie", last:"Barrett", gender:"F",
            birth:{}, death:{}, chartRef:[13], notes:"" },
  "p049": { id:"p049", first:"Frances Bennett", last:"Barrett", gender:"F",
            birth:{date:"c.9/1889", place:"Grant Parish, LA"}, death:{}, chartRef:[13],
            notes:"Spouse: Walter Lively" },
  "p050": { id:"p050", first:"Homer Marshal", last:"Barrett", gender:"M",
            birth:{date:"c.11/1891"}, death:{}, chartRef:[13],
            notes:"Married c.12/4/1908, Rapides Parish; Spouse: Lola Standley" },

  // Johnson children (from charts 21 & 22)
  "p051": { id:"p051", first:"Leopard", last:"Johnson", gender:"M", birth:{}, death:{}, chartRef:[22] },
  "p052": { id:"p052", first:"Nancy Hanna", last:"Johnson", gender:"F", birth:{}, death:{}, chartRef:[22] },
  "p053": { id:"p053", first:"Dave", last:"Johnson", gender:"M", birth:{}, death:{}, chartRef:[22] },
  "p054": { id:"p054", first:"Gid", last:"Johnson", gender:"M", birth:{}, death:{}, chartRef:[22] },
  "p055": { id:"p055", first:"Melioda", last:"Johnson", gender:"F", birth:{}, death:{}, chartRef:[22] },
  "p056": { id:"p056", first:"Arthur", last:"Johnson", gender:"M", birth:{}, death:{}, chartRef:[21,22] },
  "p057": { id:"p057", first:"Auritta", last:"Johnson", gender:"F", birth:{}, death:{}, chartRef:[21] },
  "p058": { id:"p058", first:"Noah", last:"Johnson", gender:"M", birth:{}, death:{}, chartRef:[21] },
  "p059": { id:"p059", first:"Warren", last:"Johnson", gender:"M", birth:{}, death:{}, chartRef:[21] },
  "p060": { id:"p060", first:"Jake", last:"Johnson", gender:"M", birth:{}, death:{}, chartRef:[21] },
  "p061": { id:"p061", first:"Martin", last:"Johnson", gender:"M", birth:{}, death:{}, chartRef:[21] },
  "p062": { id:"p062", first:"Narcisse", last:"Johnson", gender:"M", birth:{}, death:{}, chartRef:[21] },

  // Brown children (from chart 18)
  "p063": { id:"p063", first:"Gladys", last:"Brown", gender:"F", birth:{}, death:{}, chartRef:[18] },
  "p064": { id:"p064", first:"Clifton", last:"Brown", gender:"M", birth:{}, death:{}, chartRef:[18] },
  "p065": { id:"p065", first:"Dallas", last:"Brown", gender:"M", birth:{}, death:{}, chartRef:[18] },

  // White children (from chart 20)
  "p066": { id:"p066", first:"Henry", last:"White", gender:"M", birth:{}, death:{}, chartRef:[20] },
  "p067": { id:"p067", first:"William Bud", last:"White", gender:"M", birth:{}, death:{}, chartRef:[20] },

  // Barrett children of Rev. George (from chart 19)
  "p068": { id:"p068", first:"Elizabeth Ann", last:"Barrett", gender:"F", birth:{}, death:{}, chartRef:[19] },
  "p069": { id:"p069", first:"Cornelius", last:"Barrett", gender:"M", birth:{}, death:{}, chartRef:[19] },

  // ── GENERATION 3 ──────────────────────────────────────────────────────────
  "p100": { id:"p100", first:"Harold Lee", last:"Golden", gender:"M",
            birth:{date:"11/6/1912", place:"Allen Parish, LA"},
            death:{place:"Beaumont, TX"},
            marriage:{date:"c.12/1931", place:"Kountze, TX"},
            chartRef:[7,12], notes:"Son of James Edward Golden + Beatrice Rebecca Banks" },
  "p101": { id:"p101", first:"Louis Madine", last:"Roberts", gender:"F",
            birth:{date:"c.12/21/1901", place:"[Kountze, TX]"},
            death:{}, chartRef:[7], notes:"Wife of Harold Lee Golden" },
  "p102": { id:"p102", first:"Ernest Albert", last:"Golden", gender:"M",
            birth:{date:"4/18/1915", place:"Allen Parish, LA"},
            death:{},
            marriage:{date:"c.5/14/1939", place:"Baton Rouge, LA"},
            chartRef:[8,12], notes:"Son of James Edward Golden + Beatrice Rebecca Banks" },
  "p103": { id:"p103", first:"Marjorie Lee", last:"McVey", gender:"F",
            birth:{date:"c.4/6/1920", place:"Kansas City, MO"},
            death:{}, chartRef:[8], notes:"Wife of Ernest Albert Golden" },
  "p104": { id:"p104", first:"Hazel Ella Alice", last:"Golden", gender:"F",
            birth:{date:"c.1919", place:"[Hampton, LA]"},
            death:{},
            marriage:{date:"c.4/14/1935", place:"Graveton, TX"},
            chartRef:[9,12], notes:"Daughter of James Edward Golden + Beatrice Rebecca Banks" },
  "p105": { id:"p105", first:"Thedford Lay", last:"Hart", gender:"M",
            birth:{date:"c.4/4/1925", place:"Graveton, TX"},
            death:{}, chartRef:[9], notes:"Husband of Hazel Ella Alice Golden" },
  "p106": { id:"p106", first:"Donald Paul", last:"Golden", suffix:"Sr.", gender:"M",
            birth:{date:"c.1924", place:"[Louisiana]"},
            death:{},
            marriage:{date:"c.7/1/1962", place:"Beaumont, TX"},
            chartRef:[6,12], notes:"Son of James Edward Golden + Beatrice Rebecca Banks" },
  "p107": { id:"p107", first:"Edith Elnora", last:"Barrett", gender:"F",
            birth:{date:"c.2/1/1931", place:"Beaumont, TX (Jeff Co.)"},
            death:{}, chartRef:[6,11], notes:"Daughter of Aby Luther Barrett + Nora Lee Brown" },
  "p108": { id:"p108", first:"Lois Inez", last:"Golden", gender:"F",
            birth:{date:"c.11/27/1918"},
            death:{},
            marriage:{date:"c.11/3/1946", place:"Kountze, TX"},
            chartRef:[10,12], notes:"Daughter of James Edward Golden + Beatrice Rebecca Banks" },
  "p109": { id:"p109", first:"Harold Nathan", last:"Morgan", gender:"M",
            birth:{}, death:{}, chartRef:[10], notes:"Occupation: Bookkeeper. Husband of Lois Inez Golden" },
  "p110": { id:"p110", first:"Jimmy Bruce", last:"Golden", gender:"M",
            birth:{date:"c.4/6/1939", place:"[Kountze, TX area]"},
            death:{}, chartRef:[12], notes:"Son of James Edward Golden + Beatrice Rebecca Banks" },
  "p111": { id:"p111", first:"Helen Faye", last:"Barrett", gender:"F",
            birth:{date:"c.4/15/1944", place:"Oakdale, LA"},
            death:{}, chartRef:[11,27], notes:"Daughter of Aby Luther Barrett + Nora Lee Brown" },
  "p112": { id:"p112", first:"Gordon Evans", last:"Thomas", gender:"M",
            birth:{date:"c.4/15/1943", place:"[Fort Payne area, FL]"},
            death:{},
            marriage:{date:"c.2/3/1963", place:"Beaumont, TX (Jeff Co.)"},
            chartRef:[27], notes:"Church: Baptist. Father: [?] Stintons Sr." },

  // Babin children (from chart 16)
  "p113": { id:"p113", first:"[Bookie]", last:"Babin", gender:"U", birth:{}, death:{}, chartRef:[16] },
  "p114": { id:"p114", first:"Roy", last:"Babin", gender:"M", birth:{}, death:{}, chartRef:[16] },
  "p115": { id:"p115", first:"Paul", last:"Babin", gender:"M", birth:{}, death:{}, chartRef:[16] },
  "p116": { id:"p116", first:"Grace", last:"Babin", gender:"F", birth:{}, death:{}, chartRef:[16] },
  "p117": { id:"p117", first:"Lucille", last:"Babin", gender:"F", birth:{}, death:{}, chartRef:[16] },

  // Bransford children (from chart 17)
  "p118": { id:"p118", first:"Ivan", last:"Bransford", gender:"M", birth:{}, death:{}, chartRef:[17] },
  "p119": { id:"p119", first:"Lloyd", last:"Bransford", gender:"M", birth:{}, death:{}, chartRef:[17] },
  "p120": { id:"p120", first:"Esther", last:"Bransford", gender:"F", birth:{}, death:{}, chartRef:[17] },
  "p121": { id:"p121", first:"[?]", last:"Bransford Bond", gender:"F", birth:{}, death:{}, chartRef:[17] },

  // Hart children (from chart 9)
  "p122": { id:"p122", first:"Patricia Renee", last:"Hart", gender:"F", birth:{}, death:{}, chartRef:[9] },
  "p123": { id:"p123", first:"Nancy Yvonne", last:"Hart", gender:"F", birth:{}, death:{}, chartRef:[9] },
  "p124": { id:"p124", first:"Judith Carmen", last:"Hart", gender:"F", birth:{}, death:{}, chartRef:[9] },

  // Morgan children (from chart 10, beyond Randall/Rebecca)
  "p125": { id:"p125", first:"[MacHouse]", last:"Morgan", gender:"U", birth:{}, death:{}, chartRef:[10],
            notes:"Child of Harold Nathan Morgan + Lois Inez Golden; exact name unclear" },

  // ── GENERATION 4 ──────────────────────────────────────────────────────────
  "p200": { id:"p200", first:"Barbara Sue", last:"Golden", gender:"F",
            birth:{date:"c.6/4/1933", place:"Kountze, TX (Hardin Co.)"},
            death:{},
            marriage:{date:"c.10/29/1958"},
            chartRef:[7,36], notes:"Daughter of Harold Lee Golden + Louis Madine Roberts" },
  "p201": { id:"p201", first:"Robert Murray", last:"Brown", gender:"M",
            birth:{date:"c.4/11/1926", place:"Beaumont, TX (Jeff Co.)"},
            death:{},
            chartRef:[36], notes:"Church: Baptist; Military: US Navy. Father: Robert M. Brown" },
  "p202": { id:"p202", first:"Jolea Sue", last:"Golden", gender:"F",
            birth:{date:"c.5/11/1931", place:"Beaumont, TX"},
            death:{}, chartRef:[7,38], notes:"Daughter of Harold Lee Golden + Louis Madine Roberts" },
  "p203": { id:"p203", first:"Don Murray", last:"Viguet", suffix:"Jr.", gender:"M",
            birth:{}, death:{}, chartRef:[38],
            notes:"Husband of Jolea Sue Golden; father of Vicky Layne Viguet" },
  "p204": { id:"p204", first:"Gregory Bruce", last:"Golden", gender:"M",
            birth:{date:"c.2/14/1951", place:"Huntsville, TX"},
            death:{},
            marriage:{date:"c.11/3/1989"},
            chartRef:[8,31], notes:"Son of Ernest Albert Golden + Marjorie Lee McVey" },
  "p205": { id:"p205", first:"Almalee Davis", last:"Crumb", gender:"F",
            birth:{}, death:{}, chartRef:[31], notes:"Wife of Gregory Bruce Golden" },
  "p206": { id:"p206", first:"Michael Lee", last:"Golden", gender:"M",
            birth:{date:"c.4/5/1950", place:"[Huntsville, TX]"},
            death:{},
            marriage:{date:"c.4/1/1992", place:"Houston, TX (Harris Co.)"},
            chartRef:[8,32], notes:"Son of Ernest Albert Golden + Marjorie Lee McVey" },
  "p207": { id:"p207", first:"Christine", last:"Smith", gender:"F",
            birth:{place:"Copley, Ohio"}, death:{}, chartRef:[32], notes:"Wife of Michael Lee Golden" },
  "p208": { id:"p208", first:"Barry James", last:"Golden", gender:"M",
            birth:{date:"c.8/4/1953", place:"Huntsville, TX"},
            death:{},
            marriage:{date:"c.4/13/1975", place:"[Hobrock, TX]"},
            chartRef:[8,33], notes:"Son of Ernest Albert Golden + Marjorie Lee McVey" },
  "p209": { id:"p209", first:"Mary Lyna", last:"Lewery", gender:"F",
            birth:{date:"c.5/5/1953"}, death:{}, chartRef:[33], notes:"Wife of Barry James Golden" },
  "p210": { id:"p210", first:"Donald Paul", last:"Golden", suffix:"Jr.", gender:"M",
            birth:{date:"c.3/1946", place:"Beaumont, TX (Jeff Co.)"},
            death:{},
            marriage:{date:"c.4/28/1967", place:"Houston, TX (Harris Co.)"},
            chartRef:[6,24], notes:"Son of Donald Paul Golden Sr. + Edith Elnora Barrett. Occupation: Westinghouse/EMF" },
  "p211": { id:"p211", first:"Kathy Monfort", last:"Lucas", gender:"F",
            birth:{date:"c.3/15/1945", place:"Long Island, NY"},
            death:{}, chartRef:[24], notes:"Wife of Donald Paul Golden Jr." },
  "p212": { id:"p212", first:"Jerry Gene", last:"Golden", gender:"M",
            birth:{date:"6/7/1952", place:"Beaumont, TX (Jeff Co.)"},
            death:{},
            marriage:{date:"c.9/14/1973", place:"Beaumont, TX"},
            chartRef:[6,25], notes:"Son of Donald Paul Golden Sr. + Edith Elnora Barrett. Church: Nazarene" },
  "p213": { id:"p213", first:"Lynnedie Jeane", last:"Brookins", gender:"F",
            birth:{date:"c.4/21/1951", place:"San Antonio, TX"},
            death:{}, chartRef:[25], notes:"Wife of Jerry Gene Golden. Church: Nazarene" },
  "p214": { id:"p214", first:"Janice Lee", last:"Golden", gender:"F",
            birth:{date:"c.4/2/1955", place:"Beaumont, TX"},
            death:{},
            marriage:{date:"c.11/1969", place:"Richmond, TX (Fort Bend Co.)"},
            chartRef:[6,26], notes:"Daughter of Donald Paul Golden Sr. + Edith Elnora Barrett" },
  "p215": { id:"p215", first:"Phillip Sand", last:"Holset", suffix:"II", gender:"M",
            birth:{date:"c.4/1/1959", place:"Richmond, [VA or TX]"},
            death:{}, chartRef:[26], notes:"Husband of Janice Lee Golden" },
  "p216": { id:"p216", first:"Randall Golden", last:"Morgan", gender:"M",
            birth:{date:"c.3/28/1949"}, death:{},
            marriage:{date:"c.7/31/1969"},
            chartRef:[10,34], notes:"Son of Harold Nathan Morgan + Lois Inez Golden" },
  "p217": { id:"p217", first:"Mary Louise", last:"Chaney", gender:"F",
            birth:{}, death:{}, chartRef:[34], notes:"Wife of Randall Golden Morgan" },
  "p218": { id:"p218", first:"Rebecca Etha", last:"Morgan", gender:"F",
            birth:{date:"c.7/12/1955", place:"Beaumont, TX"},
            death:{}, chartRef:[10,35], notes:"Daughter of Harold Nathan Morgan + Lois Inez Golden" },
  "p219": { id:"p219", first:"Charles D.", last:"Landry", gender:"M",
            birth:{}, death:{}, chartRef:[35], notes:"Husband of Rebecca Etha Morgan (divorced)" },
  "p220": { id:"p220", first:"Wayne Evans", last:"Thomas", gender:"M",
            birth:{date:"c.9/4/1961", place:"Beaumont, TX (Jeff Co.)"},
            death:{},
            marriage:{date:"c.10/1985"},
            chartRef:[27,28], notes:"Son of Gordon Evans Thomas + Helen Faye Barrett. Church: Christian" },
  "p221": { id:"p221", first:"Laurie Mariame", last:"Abercrombie", gender:"F",
            birth:{date:"c.6/10/1956", place:"Beaumont, TX (Jeff Co.)"},
            death:{}, chartRef:[28], notes:"Wife of Wayne Evans Thomas. Church: Christian" },
  "p222": { id:"p222", first:"Steven Gregory", last:"Thomas", gender:"M",
            birth:{place:"Beaumont, TX (Jeff Co.)"},
            death:{},
            marriage:{date:"c.4/12/1974", place:"Beaumont, TX"},
            chartRef:[27,29], notes:"Son of Gordon Evans Thomas + Helen Faye Barrett. Church: Christian" },
  "p223": { id:"p223", first:"Gladys Ann", last:"Golden", gender:"F",
            birth:{date:"c.4/4/1948", place:"Beaumont, TX"},
            death:{}, chartRef:[29], notes:"Wife of Steven Gregory Thomas" },
  "p224": { id:"p224", first:"Patricia Ann", last:"Thomas", gender:"F",
            birth:{date:"c.4/15/1953", place:"Beaumont, TX (Jeff Co.)"},
            death:{}, chartRef:[27,30],
            notes:"Daughter of Gordon Evans Thomas + Helen Faye Barrett" },
  "p225": { id:"p225", first:"Carlton David", last:"[Chitty?]", gender:"M",
            birth:{}, death:{}, chartRef:[30],
            notes:"Husband of Patricia Ann Thomas; surname unclear in chart" },
  "p226": { id:"p226", first:"Linda Faye", last:"Thomas", gender:"F",
            birth:{}, death:{}, chartRef:[27], notes:"Daughter of Gordon Evans Thomas + Helen Faye Barrett" },

  // ── GENERATION 5 ──────────────────────────────────────────────────────────
  "p300": { id:"p300", first:"Kim", last:"Brown", gender:"F",
            birth:{date:"c.5/30/1953", place:"Beaumont, TX (Jeff Co.)"},
            death:{}, chartRef:[36,37], notes:"Daughter of Robert Murray Brown + Barbara Sue Golden" },
  "p301": { id:"p301", first:"Charles Jude", last:"Giglio", gender:"M",
            birth:{}, death:{}, chartRef:[37], notes:"Husband of Kim Brown" },
  "p302": { id:"p302", first:"Kerry Antoinette", last:"Brown", gender:"F",
            birth:{}, death:{}, chartRef:[36], notes:"Daughter of Robert Murray Brown + Barbara Sue Golden" },
  "p303": { id:"p303", first:"John David", last:"Brown", gender:"M",
            birth:{}, death:{}, chartRef:[36], notes:"Son of Robert Murray Brown + Barbara Sue Golden" },
  "p304": { id:"p304", first:"Vicky Layne", last:"Viguet", gender:"F",
            birth:{date:"c.4/9/1953", place:"Beaumont, TX"},
            death:{},
            marriage:{date:"c.4/10/1977", place:"Beaumont, TX (Jeff Co.)"},
            chartRef:[38], notes:"Daughter of Don Murray Viguet Jr. + Jolea Sue Golden" },
  "p305": { id:"p305", first:"Thomas James", last:"Vaes", suffix:"Jr.", gender:"M",
            birth:{place:"Beaumont, TX area"}, death:{}, chartRef:[38], notes:"Husband of Vicky Layne Viguet" },
  "p306": { id:"p306", first:"Gregory Collins", last:"Golden", gender:"M",
            birth:{},
            marriage:{date:"c.9/30/1977", place:"New Orleans, LA (Jeff Parish)"},
            chartRef:[25], notes:"Son of Jerry Gene Golden + Lynnedie Jeane Brookins" },
  "p307": { id:"p307", first:"Robert Michael", last:"Golden", gender:"M",
            birth:{date:"c.4/12/1974", place:"New Orleans, LA (Jeff Parish)"},
            chartRef:[25], notes:"Son of Jerry Gene Golden + Lynnedie Jeane Brookins" },
  "p308": { id:"p308", first:"Zachary Sand", last:"Holset", gender:"M",
            birth:{}, death:{}, chartRef:[26], notes:"Son of Phillip Sand Holset II + Janice Lee Golden" },
  "p309": { id:"p309", first:"Britany Carin", last:"Golden", gender:"F",
            birth:{date:"c.1968", place:"Houston, TX (Harris Co.)"},
            death:{},
            marriage:{date:"c.7/2/1988", place:"Nacogdoches, TX"},
            chartRef:[24,39], notes:"Daughter of Donald Paul Golden Jr. + Kathy Monfort Lucas" },
  "p310": { id:"p310", first:"[?]", last:"Webb", gender:"M",
            birth:{date:"c.4/11/1963", place:"[Fredonia, TX]"},
            death:{}, chartRef:[39],
            notes:"Husband of Britany Carin Golden. Church: Church of Christ" },
  "p311": { id:"p311", first:"Patrick Scott", last:"Golden", gender:"M",
            birth:{date:"c.9/10/1970", place:"Houston, TX (Harris Co.)"},
            death:{}, chartRef:[24], notes:"Son of Donald Paul Golden Jr. + Kathy Monfort Lucas" },
  "p312": { id:"p312", first:"Matthew", last:"Golden", gender:"M",
            birth:{}, death:{}, chartRef:[31], notes:"Son of Gregory Bruce Golden + Almalee Davis Crumb" },
  "p313": { id:"p313", first:"Barbara", last:"Golden", gender:"F",
            birth:{}, death:{}, chartRef:[31], notes:"Daughter of Gregory Bruce Golden + Almalee Davis Crumb" },
  "p314": { id:"p314", first:"David", last:"Golden", gender:"M",
            birth:{}, death:{}, chartRef:[31], notes:"Son of Gregory Bruce Golden + Almalee Davis Crumb" },
  "p315": { id:"p315", first:"Daniel", last:"Golden", gender:"M",
            birth:{}, death:{}, chartRef:[31], notes:"Son of Gregory Bruce Golden + Almalee Davis Crumb" },
  "p316": { id:"p316", first:"Michael Patrick", last:"Golden", gender:"M",
            birth:{date:"c.4/23/1981", place:"Houston, TX (Harris Co.)"},
            death:{}, chartRef:[32], notes:"Son of Michael Lee Golden + Christine Smith" },
  "p317": { id:"p317", first:"Lance", last:"Morgan", gender:"M",
            birth:{date:"c.4/9/1971"}, death:{}, chartRef:[34],
            notes:"Son of Randall Golden Morgan + Mary Louise Chaney" },
  "p318": { id:"p318", first:"Lee", last:"Morgan", gender:"M",
            birth:{date:"c.4/5/1975"}, death:{}, chartRef:[34],
            notes:"Son of Randall Golden Morgan + Mary Louise Chaney" },
  "p319": { id:"p319", first:"Taci Chantal", last:"Landry", gender:"F",
            birth:{date:"c.1988", place:"Beaumont, TX"},
            death:{}, chartRef:[35],
            notes:"Daughter of Charles D. Landry + Rebecca Etha Morgan" },
  "p320": { id:"p320", first:"Tara Marie", last:"Thomas", gender:"F",
            birth:{}, death:{}, chartRef:[28], notes:"Daughter of Wayne Evans Thomas + Laurie Mariame Abercrombie" },
  "p321": { id:"p321", first:"Shane Allen", last:"Thomas", gender:"M",
            birth:{date:"c.7/12/1982", place:"Beaumont, TX (Jeff Co.)"},
            death:{}, chartRef:[28], notes:"Son of Wayne Evans Thomas + Laurie Mariame Abercrombie" },
  "p322": { id:"p322", first:"William Barrett", last:"Thomas", gender:"M",
            birth:{date:"c.7/13/1971", place:"Beaumont, TX (Jeff Co.)"},
            death:{}, chartRef:[29], notes:"Son of Steven Gregory Thomas + Gladys Ann Golden" },
  "p323": { id:"p323", first:"Stormair Ann", last:"Thomas", gender:"F",
            birth:{date:"c.4/11/1978", place:"Beaumont, TX"},
            death:{}, chartRef:[29], notes:"Daughter of Steven Gregory Thomas + Gladys Ann Golden" },
  "p324": { id:"p324", first:"Gregory Ryan", last:"Thomas", gender:"M",
            birth:{date:"c.6/16/1971", place:"Beaumont, TX"},
            death:{}, chartRef:[29], notes:"Son of Steven Gregory Thomas + Gladys Ann Golden" },
  "p325": { id:"p325", first:"Joshua David", last:"[?]", gender:"M",
            birth:{date:"c.7/31/1993", place:"Beaumont, TX (Jeff Co.)"},
            death:{}, chartRef:[30], notes:"Son of Carlton David [?] + Patricia Ann Thomas" },
  "p326": { id:"p326", first:"Julee Ann", last:"[?]", gender:"F",
            birth:{date:"c.2003", place:"Beaumont, TX (Jeff Co.)"},
            death:{}, chartRef:[30], notes:"Daughter of Carlton David [?] + Patricia Ann Thomas" },

  // ── GENERATION 6 ──────────────────────────────────────────────────────────
  "p400": { id:"p400", first:"Kristen", last:"Giglio", gender:"F",
            birth:{date:"c.9/8/1977"}, death:{}, chartRef:[37],
            notes:"Daughter of Charles Jude Giglio + Kim Brown" },
  "p401": { id:"p401", first:"Gina", last:"Giglio", gender:"F",
            birth:{date:"c.1/2/1980"}, death:{}, chartRef:[37],
            notes:"Daughter of Charles Jude Giglio + Kim Brown" },
  "p402": { id:"p402", first:"Ryan", last:"Vaes", gender:"M",
            birth:{date:"c.4/1/1978"}, death:{}, chartRef:[38],
            notes:"Son of Thomas James Vaes Jr. + Vicky Layne Viguet" },
  "p403": { id:"p403", first:"Shannon", last:"Vaes", gender:"F",
            birth:{date:"c.10/21/1981"}, death:{}, chartRef:[38],
            notes:"Daughter of Thomas James Vaes Jr. + Vicky Layne Viguet" },
  "p404": { id:"p404", first:"Sarah-Nicole", last:"Webb", gender:"F",
            birth:{date:"c.1991"}, death:{}, chartRef:[39],
            notes:"Daughter of [?] Webb + Britany Carin Golden" },
};

const FAMILIES = [
  // ── GEN 0→1 ──────────────────────────────────────────────────────────────
  { id:"f001", husbandId:"p003", wifeId:"p004", marriage:{}, childIds:["p015"], chartRef:22,
    notes:"Parents of Louise Clack" },
  { id:"f002", husbandId:"p001", wifeId:"p002", marriage:{}, childIds:["p014"], chartRef:21,
    notes:"Parents of Benoit Johnson" },

  // ── GEN 1 (primary couples) ───────────────────────────────────────────────
  { id:"f010", husbandId:"p010", wifeId:"p011", marriage:{place:"[TX]"},
    childIds:["p030","p038","p040"], chartRef:14,
    notes:"Albert Golden + Ella Littleton" },
  { id:"f011", husbandId:"p012", wifeId:"p013", marriage:{},
    childIds:["p042","p043","p032"], chartRef:23,
    notes:"Charles Frederick Banks + Celestine Aymond" },
  { id:"f012", husbandId:"p014", wifeId:"p015", marriage:{},
    childIds:["p051","p052","p053","p054","p055","p033","p056"], chartRef:22,
    notes:"Benoit Johnson + Louise Clack" },
  { id:"f013", husbandId:"p014", wifeId:"p016", marriage:{},
    childIds:["p057","p058","p059","p060","p061","p062","p056"], chartRef:21,
    notes:"Benoit Johnson + Susan Clack (possibly second/first wife)" },
  { id:"f014", husbandId:"p017", wifeId:"p018", marriage:{place:"Mississippi"},
    childIds:["p034","p068","p069"], chartRef:19,
    notes:"Rev. George H. Barrett + Sarah" },
  { id:"f015", husbandId:"p019", wifeId:"p020", marriage:{},
    childIds:["p035","p066","p067"], chartRef:20,
    notes:"Edward M. White + Nancy Ann Hall" },
  { id:"f016", husbandId:"p021", wifeId:"p022", marriage:{},
    childIds:["p037","p063","p064","p065"], chartRef:18,
    notes:"William Joseph Brown + Berta Lou Mildred Evans" },

  // ── GEN 2 couples ────────────────────────────────────────────────────────
  { id:"f020", husbandId:"p030", wifeId:"p031",
    marriage:{date:"9/30/1911", place:"Lake Charles, LA"},
    childIds:["p100","p102","p104","p106","p108","p110"], chartRef:12,
    notes:"James Edward Golden + Beatrice Rebecca Banks" },
  { id:"f021", husbandId:"p032", wifeId:"p033",
    marriage:{date:"c.4/15/1900", place:"Forest Hill, LA (Butler Cemetery)"},
    childIds:["p031"], chartRef:15,
    notes:"Robert E. Lee Herman Banks + Alice Johnson — Beatrice Rebecca Banks is their daughter" },
  { id:"f022", husbandId:"p034", wifeId:"p035", marriage:{},
    childIds:["p044","p045","p046","p047","p048","p049","p050","p036"], chartRef:13,
    notes:"Henry Benson Barrett + Elizabeth Jane White" },
  { id:"f023", husbandId:"p036", wifeId:"p037",
    marriage:{},
    childIds:["p107","p111"], chartRef:11,
    notes:"Aby Luther Barrett + Nora Lee Brown" },
  { id:"f024", husbandId:"p039", wifeId:"p038", marriage:{},
    childIds:["p113","p114","p115","p116","p117"], chartRef:16,
    notes:"Dee Babin + Frances (Fannie) Golden" },
  { id:"f025", husbandId:"p041", wifeId:"p040", marriage:{},
    childIds:["p118","p119","p120","p121"], chartRef:17,
    notes:"[?] Bransford + Kitty Golden" },

  // ── GEN 3 couples ────────────────────────────────────────────────────────
  { id:"f030", husbandId:"p100", wifeId:"p101",
    marriage:{date:"c.12/1931", place:"Kountze, TX"},
    childIds:["p200","p202"], chartRef:7,
    notes:"Harold Lee Golden + Louis Madine Roberts" },
  { id:"f031", husbandId:"p102", wifeId:"p103",
    marriage:{date:"c.5/14/1939", place:"Baton Rouge, LA"},
    childIds:["p204","p206","p208"], chartRef:8,
    notes:"Ernest Albert Golden + Marjorie Lee McVey" },
  { id:"f032", husbandId:"p105", wifeId:"p104", marriage:{date:"c.4/14/1935", place:"Graveton, TX"},
    childIds:["p122","p123","p124"], chartRef:9,
    notes:"Thedford Lay Hart + Hazel Ella Alice Golden" },
  { id:"f033", husbandId:"p106", wifeId:"p107",
    marriage:{date:"c.7/1/1962", place:"Beaumont, TX"},
    childIds:["p210","p212","p214"], chartRef:6,
    notes:"Donald Paul Golden Sr. + Edith Elnora Barrett" },
  { id:"f034", husbandId:"p109", wifeId:"p108",
    marriage:{date:"c.11/3/1946", place:"Kountze, TX"},
    childIds:["p216","p218","p125"], chartRef:10,
    notes:"Harold Nathan Morgan + Lois Inez Golden" },
  { id:"f035", husbandId:"p112", wifeId:"p111",
    marriage:{date:"c.2/3/1963", place:"Beaumont, TX"},
    childIds:["p226","p220","p222","p224"], chartRef:27,
    notes:"Gordon Evans Thomas + Helen Faye Barrett" },

  // ── GEN 4 couples ────────────────────────────────────────────────────────
  { id:"f040", husbandId:"p201", wifeId:"p200",
    marriage:{date:"c.10/29/1958"},
    childIds:["p300","p302","p303"], chartRef:36,
    notes:"Robert Murray Brown + Barbara Sue Golden" },
  { id:"f041", husbandId:"p203", wifeId:"p202", marriage:{},
    childIds:["p304"], chartRef:38,
    notes:"Don Murray Viguet Jr. + Jolea Sue Golden" },
  { id:"f042", husbandId:"p204", wifeId:"p205",
    marriage:{date:"c.11/3/1989"},
    childIds:["p312","p313","p314","p315"], chartRef:31,
    notes:"Gregory Bruce Golden + Almalee Davis Crumb" },
  { id:"f043", husbandId:"p206", wifeId:"p207",
    marriage:{date:"c.4/1/1992", place:"Houston, TX"},
    childIds:["p316"], chartRef:32,
    notes:"Michael Lee Golden + Christine Smith" },
  { id:"f044", husbandId:"p208", wifeId:"p209",
    marriage:{date:"c.4/13/1975"},
    childIds:[], chartRef:33,
    notes:"Barry James Golden + Mary Lyna Lewery" },
  { id:"f045", husbandId:"p210", wifeId:"p211",
    marriage:{date:"c.4/28/1967", place:"Houston, TX"},
    childIds:["p309","p311"], chartRef:24,
    notes:"Donald Paul Golden Jr. + Kathy Monfort Lucas" },
  { id:"f046", husbandId:"p212", wifeId:"p213",
    marriage:{date:"c.9/14/1973", place:"Beaumont, TX"},
    childIds:["p306","p307"], chartRef:25,
    notes:"Jerry Gene Golden + Lynnedie Jeane Brookins" },
  { id:"f047", husbandId:"p215", wifeId:"p214",
    marriage:{date:"c.11/1969", place:"Richmond, TX"},
    childIds:["p308"], chartRef:26,
    notes:"Phillip Sand Holset II + Janice Lee Golden" },
  { id:"f048", husbandId:"p216", wifeId:"p217",
    marriage:{date:"c.7/31/1969"},
    childIds:["p317","p318"], chartRef:34,
    notes:"Randall Golden Morgan + Mary Louise Chaney" },
  { id:"f049", husbandId:"p219", wifeId:"p218", marriage:{},
    childIds:["p319"], chartRef:35,
    notes:"Charles D. Landry + Rebecca Etha Morgan (divorced)" },
  { id:"f050", husbandId:"p220", wifeId:"p221",
    marriage:{date:"c.10/1985"},
    childIds:["p320","p321"], chartRef:28,
    notes:"Wayne Evans Thomas + Laurie Mariame Abercrombie" },
  { id:"f051", husbandId:"p222", wifeId:"p223",
    marriage:{date:"c.4/12/1974", place:"Beaumont, TX"},
    childIds:["p322","p323","p324"], chartRef:29,
    notes:"Steven Gregory Thomas + Gladys Ann Golden" },
  { id:"f052", husbandId:"p225", wifeId:"p224", marriage:{},
    childIds:["p325","p326"], chartRef:30,
    notes:"Carlton David [?] + Patricia Ann Thomas" },

  // ── GEN 5 couples ────────────────────────────────────────────────────────
  { id:"f060", husbandId:"p301", wifeId:"p300",
    marriage:{},
    childIds:["p400","p401"], chartRef:37,
    notes:"Charles Jude Giglio + Kim Brown" },
  { id:"f061", husbandId:"p305", wifeId:"p304",
    marriage:{date:"c.4/10/1977", place:"Beaumont, TX"},
    childIds:["p402","p403"], chartRef:38,
    notes:"Thomas James Vaes Jr. + Vicky Layne Viguet" },
  { id:"f062", husbandId:"p310", wifeId:"p309",
    marriage:{date:"c.7/2/1988", place:"Nacogdoches, TX"},
    childIds:["p404"], chartRef:39,
    notes:"[?] Webb + Britany Carin Golden" },
];

// Build lookup: personId → family they belong to as a child
const BIRTH_FAMILY = {};
FAMILIES.forEach(f => {
  f.childIds.forEach(cid => { BIRTH_FAMILY[cid] = f.id; });
});

// Build lookup: personId → families they appear in as spouse
const SPOUSE_FAMILIES = {};
FAMILIES.forEach(f => {
  [f.husbandId, f.wifeId].forEach(pid => {
    if (!SPOUSE_FAMILIES[pid]) SPOUSE_FAMILIES[pid] = [];
    SPOUSE_FAMILIES[pid].push(f.id);
  });
});

// Chart metadata
const CHART_INFO = {
  1:  { type:"pedigree", title:"Ancestor Chart No. 2 — Charles Johnson II line" },
  2:  { type:"pedigree", title:"Ancestor Chart No. 3 — Johnson line continued" },
  3:  { type:"pedigree", title:"Ancestor Chart No. 4 — [Marie Sellie] line" },
  4:  { type:"pedigree", title:"Ancestor Chart No. 5 — [DuBe / Devers] line" },
  5:  { type:"pedigree", title:"Ancestor Chart No. 6 — [Francoise / Fontenot] line" },
  6:  { type:"family", title:"Donald Paul Golden Sr. + Edith Elnora Barrett" },
  7:  { type:"family", title:"Harold Lee Golden + Louis Madine Roberts" },
  8:  { type:"family", title:"Ernest Albert Golden + Marjorie Lee McVey" },
  9:  { type:"family", title:"Thedford Lay Hart + Hazel Ella Alice Golden" },
  10: { type:"family", title:"Harold Nathan Morgan + Lois Inez Golden" },
  11: { type:"family", title:"Aby Luther Barrett + Nora Lee Brown" },
  12: { type:"family", title:"James Edward Golden + Beatrice Rebecca Banks" },
  13: { type:"family", title:"Henry Benson Barrett + Elizabeth Jane White" },
  14: { type:"family", title:"Albert Golden + Ella Littleton" },
  15: { type:"family", title:"Robert E. Lee Herman Banks + Alice Johnson" },
  16: { type:"family", title:"Dee Babin + Frances (Fannie) Golden" },
  17: { type:"family", title:"[?] Bransford + Kitty Golden" },
  18: { type:"family", title:"William Joseph Brown + Berta Lou Mildred Evans" },
  19: { type:"family", title:"Rev. George H. Barrett + Sarah" },
  20: { type:"family", title:"Edward M. White + Nancy Ann Hall" },
  21: { type:"family", title:"Benoit Johnson + Susan Clack" },
  22: { type:"family", title:"Benoit Johnson + Louise Clack" },
  23: { type:"family", title:"Charles Frederick Banks + Celestine Aymond" },
  24: { type:"family", title:"Donald Paul Golden Jr. + Kathy Monfort Lucas" },
  25: { type:"family", title:"Jerry Gene Golden + Lynnedie Jeane Brookins" },
  26: { type:"family", title:"Phillip Sand Holset II + Janice Lee Golden" },
  27: { type:"family", title:"Gordon Evans Thomas + Helen Faye Barrett" },
  28: { type:"family", title:"Wayne Evans Thomas + Laurie Mariame Abercrombie" },
  29: { type:"family", title:"Steven Gregory Thomas + Gladys Ann Golden" },
  30: { type:"family", title:"Carlton David [?] + Patricia Ann Thomas" },
  31: { type:"family", title:"Gregory Bruce Golden + Almalee Davis Crumb" },
  32: { type:"family", title:"Michael Lee Golden + Christine Smith" },
  33: { type:"family", title:"Barry James Golden + Mary Lyna Lewery" },
  34: { type:"family", title:"Randall Golden Morgan + Mary Louise Chaney" },
  35: { type:"family", title:"Charles D. Landry + Rebecca Etha Morgan" },
  36: { type:"family", title:"Robert Murray Brown + Barbara Sue Golden" },
  37: { type:"family", title:"Charles Jude Giglio + Kim Brown" },
  38: { type:"family", title:"Thomas James Vaes Jr. + Vicky Layne Viguet" },
  39: { type:"family", title:"[?] Webb + Britany Carin Golden" },
};
